### Get All Users
GET http://localhost:5233/api/home/GetAllUsers
Accept: application/json

### Upadate User by Id
PUT http://localhost:5233/api/home/UpdateUserById
Content-Type: application/json
Accept: application/json


{
    "UserId": "655de2e8-ff55-4dc9-b7bf-652f415f7930",
    "UserName":"Kadds"
}
### Get User by Id
POST http://localhost:5233/api/home/GetById
Content-Type: application/json
Accept: application/json

{
  "UserId":"376a06cb-f492-4836-a202-74fb09f38050"
}


### Add New User
POST http://localhost:5233/api/home/AddUser
Content-Type: application/json
Accept: application/json

{
  "UserId": "376a06cb-f492-4836-a202-74fb09f38050",
  "UserName":"Kamal"

}


### Delete User by Id
DELETE http://localhost:5233/api/home/DeleteUserById
Content-Type: application/json
Accept: application/json

{
  "UserId": "3875b15b-616f-4f96-b190-b8cf25e329ce"
}



### Add Project by User ID
POST http://localhost:5233/Project/AddProByUserId
Content-Type: application/json
Accept: application/json

{
  "userId": "376a06cb-f492-4836-a202-74fb09f38050",
  "projectName": "CheckProject1"
}


### Get Project by User ID
POST http://localhost:5233/Project/GetProByUserId
Content-Type: application/json
Accept: application/json

{
  "userId":"32a11df4-15f4-4ad9-933a-1934f8fdb2a1"
}

###Update Project by projectId
PUT http://localhost:5233/Project/UpdateProById
Content-Type: application/json
Accept: application/json


{
    "projectId": "ab0b72cf-9f1d-454a-ab0e-058337cc16b7",
    "projectName":"final"
}

### Delete Project by ID
DELETE http://localhost:5233/Project/DelProById
Content-Type: application/json
Accept: application/json

{
  "projectId": "99816d4d-1b5d-405e-ba7e-f2641545b106"
}



### Get Tasks by Project ID
POST http://localhost:5233/TaskContoller/GetTasksByProId
Content-Type: application/json
Accept: application/json

{
   "projectId":"ac0dad00-3cc1-4e8a-bd63-8a830c0df871"
}


### Add Task by Project ID
POST http://localhost:5233/TaskContoller/AddTaskByProjectId
Content-Type: application/json
Accept: application/json

{
  
  "projectId": "ac0dad00-3cc1-4e8a-bd63-8a830c0df871",
  "TaskName": "pending"
}


### Delete Task by Task ID
DELETE http://localhost:5233/TaskContoller/DeleteTaskByTaskId
Content-Type: application/json
Accept: application/json

{
  "taskId": "cdfa998e-fc4c-43b8-0511-08dd57eda569"
}


### Update Task by Task ID
PUT http://localhost:5233/TaskContoller/UpdateTaskByTaskId
Content-Type: application/json
Accept: application/json

{
  "taskId": "b5bcb08a-c412-49e6-181d-08dd57ee0af2",
  
  "taskName": "Updated"
}
